## The property file will be read from ,cloud-config-server which is deployed on
## http://localhost:8888,
## cloud-config-server reads from https://github.com/kiranrchitragar/cloud-config-server,
## Files are created in repo with name : user-microservice-dev.yml
## profile.active is read from here to read the environment specific file.
spring:
  application:
    name: product-microservice
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
    # If cloud-config-server is down it takes the properties from
    # local mentioned files in the project, based on profiles.active
    # import: optional:cloud-config-server:http//localhost:8888
